/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package todos.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import todos.model.TodoItem;
import todos.model.TodoItemModel;
import todos.model.TodoItemSoap;

/**
 * The base model implementation for the TodoItem service. Represents a row in the &quot;JB_TodoItem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TodoItemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TodoItemImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TodoItemImpl
 * @generated
 */
@JSON(strict = true)
public class TodoItemModelImpl
	extends BaseModelImpl<TodoItem> implements TodoItemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a todo item model instance should use the <code>TodoItem</code> interface instead.
	 */
	public static final String TABLE_NAME = "JB_TodoItem";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"todoItemId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"priority", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("todoItemId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JB_TodoItem (uuid_ VARCHAR(75) null,todoItemId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,description VARCHAR(75) null,priority INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table JB_TodoItem";

	public static final String ORDER_BY_JPQL =
		" ORDER BY todoItem.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JB_TodoItem.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TodoItem toModel(TodoItemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TodoItem model = new TodoItemImpl();

		model.setUuid(soapModel.getUuid());
		model.setTodoItemId(soapModel.getTodoItemId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setPriority(soapModel.getPriority());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TodoItem> toModels(TodoItemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TodoItem> models = new ArrayList<TodoItem>(soapModels.length);

		for (TodoItemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TodoItemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _todoItemId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTodoItemId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _todoItemId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TodoItem.class;
	}

	@Override
	public String getModelClassName() {
		return TodoItem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TodoItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TodoItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TodoItem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TodoItem)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TodoItem, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TodoItem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TodoItem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TodoItem, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TodoItem, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TodoItem>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TodoItem.class.getClassLoader(), TodoItem.class,
			ModelWrapper.class);

		try {
			Constructor<TodoItem> constructor =
				(Constructor<TodoItem>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<TodoItem, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TodoItem, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TodoItem, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TodoItem, Object>>();
		Map<String, BiConsumer<TodoItem, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TodoItem, ?>>();

		attributeGetterFunctions.put("uuid", TodoItem::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<TodoItem, String>)TodoItem::setUuid);
		attributeGetterFunctions.put("todoItemId", TodoItem::getTodoItemId);
		attributeSetterBiConsumers.put(
			"todoItemId", (BiConsumer<TodoItem, Long>)TodoItem::setTodoItemId);
		attributeGetterFunctions.put("groupId", TodoItem::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<TodoItem, Long>)TodoItem::setGroupId);
		attributeGetterFunctions.put("companyId", TodoItem::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<TodoItem, Long>)TodoItem::setCompanyId);
		attributeGetterFunctions.put("userId", TodoItem::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TodoItem, Long>)TodoItem::setUserId);
		attributeGetterFunctions.put("userName", TodoItem::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<TodoItem, String>)TodoItem::setUserName);
		attributeGetterFunctions.put("createDate", TodoItem::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<TodoItem, Date>)TodoItem::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", TodoItem::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TodoItem, Date>)TodoItem::setModifiedDate);
		attributeGetterFunctions.put("name", TodoItem::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<TodoItem, String>)TodoItem::setName);
		attributeGetterFunctions.put("description", TodoItem::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<TodoItem, String>)TodoItem::setDescription);
		attributeGetterFunctions.put("priority", TodoItem::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<TodoItem, Integer>)TodoItem::setPriority);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTodoItemId() {
		return _todoItemId;
	}

	@Override
	public void setTodoItemId(long todoItemId) {
		_todoItemId = todoItemId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_priority = priority;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TodoItem.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TodoItem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TodoItem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TodoItem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TodoItemImpl todoItemImpl = new TodoItemImpl();

		todoItemImpl.setUuid(getUuid());
		todoItemImpl.setTodoItemId(getTodoItemId());
		todoItemImpl.setGroupId(getGroupId());
		todoItemImpl.setCompanyId(getCompanyId());
		todoItemImpl.setUserId(getUserId());
		todoItemImpl.setUserName(getUserName());
		todoItemImpl.setCreateDate(getCreateDate());
		todoItemImpl.setModifiedDate(getModifiedDate());
		todoItemImpl.setName(getName());
		todoItemImpl.setDescription(getDescription());
		todoItemImpl.setPriority(getPriority());

		todoItemImpl.resetOriginalValues();

		return todoItemImpl;
	}

	@Override
	public int compareTo(TodoItem todoItem) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), todoItem.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TodoItem)) {
			return false;
		}

		TodoItem todoItem = (TodoItem)obj;

		long primaryKey = todoItem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TodoItemModelImpl todoItemModelImpl = this;

		todoItemModelImpl._originalUuid = todoItemModelImpl._uuid;

		todoItemModelImpl._originalGroupId = todoItemModelImpl._groupId;

		todoItemModelImpl._setOriginalGroupId = false;

		todoItemModelImpl._originalCompanyId = todoItemModelImpl._companyId;

		todoItemModelImpl._setOriginalCompanyId = false;

		todoItemModelImpl._setModifiedDate = false;

		todoItemModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TodoItem> toCacheModel() {
		TodoItemCacheModel todoItemCacheModel = new TodoItemCacheModel();

		todoItemCacheModel.uuid = getUuid();

		String uuid = todoItemCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			todoItemCacheModel.uuid = null;
		}

		todoItemCacheModel.todoItemId = getTodoItemId();

		todoItemCacheModel.groupId = getGroupId();

		todoItemCacheModel.companyId = getCompanyId();

		todoItemCacheModel.userId = getUserId();

		todoItemCacheModel.userName = getUserName();

		String userName = todoItemCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			todoItemCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			todoItemCacheModel.createDate = createDate.getTime();
		}
		else {
			todoItemCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			todoItemCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			todoItemCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		todoItemCacheModel.name = getName();

		String name = todoItemCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			todoItemCacheModel.name = null;
		}

		todoItemCacheModel.description = getDescription();

		String description = todoItemCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			todoItemCacheModel.description = null;
		}

		todoItemCacheModel.priority = getPriority();

		return todoItemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TodoItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TodoItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TodoItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TodoItem)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TodoItem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TodoItem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TodoItem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TodoItem)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TodoItem>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _todoItemId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _description;
	private int _priority;
	private long _columnBitmask;
	private TodoItem _escapedModel;

}